image: ubuntu
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true

before_build:
  # Display .NET Core version
  - dotnet --version
  - dotnet restore ./dotnet-tarball-cleanup/dotnet-tarball-cleanup.csproj --verbosity m

build_script:
  - dotnet build -c Release ./dotnet-tarball-cleanup/dotnet-tarball-cleanup.csproj
  - dotnet publish -c Release -o ./artifacts  ./dotnet-tarball-cleanup/dotnet-tarball-cleanup.csproj

artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet

deploy:
- provider: NuGet
  api_key:
    secure: lWdb5HC5lSqY9HB5WC6BppCvDcQmHbf2lwizVAHIgopsMjCxUvbEOBeB84bgEyMn
  on:
    branch: master
    appveyor_repo_tag: true